<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\District;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
        	[ 'district_name' => 'Abim'],
			[ 'district_name' => 'Adjumani'],
			[ 'district_name' => 'Agago'],
			[ 'district_name' => 'Alebtong'],
			[ 'district_name' => 'Amolatar'],
			[ 'district_name' => 'Amudat'],
			[ 'district_name' => 'Amuria'],
			[ 'district_name' => 'Amuru'],
			[ 'district_name' => 'Apac'],
			[ 'district_name' => 'Arua'],
			[ 'district_name' => 'Budaka'],
			[ 'district_name' => 'Bududa'],
			[ 'district_name' => 'Bugiri'],
			[ 'district_name' => 'Bugweri'],
			[ 'district_name' => 'Buhweju'],
			[ 'district_name' => 'Buikwe'],
			[ 'district_name' => 'Bukedea'],
			[ 'district_name' => 'Bukomansimbi'],
			[ 'district_name' => 'Bukwo'],
			[ 'district_name' => 'Bulambuli'],
			[ 'district_name' => 'Buliisa'],
			[ 'district_name' => 'Bundibugyo'],
			[ 'district_name' => 'Bunyangabu'],
			[ 'district_name' => 'Bushenyi'],
			[ 'district_name' => 'Busia'],
			[ 'district_name' => 'Butaleja'],
			[ 'district_name' => 'Butambala'],
			[ 'district_name' => 'Butebo'],
			[ 'district_name' => 'Buvuma'],
			[ 'district_name' => 'Buyende'],
			[ 'district_name' => 'Dokolo'],
			[ 'district_name' => 'Gomba'],
			[ 'district_name' => 'Gulu'],
			[ 'district_name' => 'Hoima'],
			[ 'district_name' => 'Ibanda'],
			[ 'district_name' => 'Iganga'],
			[ 'district_name' => 'Isingiro'],
			[ 'district_name' => 'Jinja'],
			[ 'district_name' => 'Kaabong'],
			[ 'district_name' => 'Kabale'],
			[ 'district_name' => 'Kabarole'],
			[ 'district_name' => 'Kaberamaido'],
			[ 'district_name' => 'Kagadi'],
			[ 'district_name' => 'Kakumiro'],
			[ 'district_name' => 'Kalangala'],
			[ 'district_name' => 'Kaliro'],
			[ 'district_name' => 'Kalungu'],
			[ 'district_name' => 'Kampala'],
			[ 'district_name' => 'Kamuli'],
			[ 'district_name' => 'Kamwenge'],
			[ 'district_name' => 'Kanungu'],
			[ 'district_name' => 'Kapchorwa'],
			[ 'district_name' => 'Kapelebyong'],
			[ 'district_name' => 'Kasanda'],
			[ 'district_name' => 'Kasese'],
			[ 'district_name' => 'Katakwi'],
			[ 'district_name' => 'Katerere'],
			[ 'district_name' => 'Kayunga'],
			[ 'district_name' => 'Kibaale'],
			[ 'district_name' => 'Kibingo'],
			[ 'district_name' => 'Kiboga'],
			[ 'district_name' => 'Kibuku'],
			[ 'district_name' => 'Kikuube'],
			[ 'district_name' => 'Kiruhura'],
			[ 'district_name' => 'Kiryandongo'],
			[ 'district_name' => 'Kisoro'],
			[ 'district_name' => 'Kitgum'],
			[ 'district_name' => 'Koboko'],
			[ 'district_name' => 'Kole'],
			[ 'district_name' => 'Kotido'],
			[ 'district_name' => 'Kumi'],
			[ 'district_name' => 'Kwania'],
			[ 'district_name' => 'Kween'],
			[ 'district_name' => 'Kyankwanzi'],
			[ 'district_name' => 'Kyegegwa'],
			[ 'district_name' => 'Kyenjojo'],
			[ 'district_name' => 'Kyotera'],
			[ 'district_name' => 'Lamwo'],
			[ 'district_name' => 'Lira'],
			[ 'district_name' => 'Luuka'],
			[ 'district_name' => 'Luweero'],
			[ 'district_name' => 'Lwengo'],
			[ 'district_name' => 'Lyantonde'],
			[ 'district_name' => 'Manafwa'],
			[ 'district_name' => 'Maracha'],
			[ 'district_name' => 'Masaka'],
			[ 'district_name' => 'Masindi'],
			[ 'district_name' => 'Mayuge'],
			[ 'district_name' => 'Mbale'],
			[ 'district_name' => 'Mbarara'],
			[ 'district_name' => 'Mitooma'],
			[ 'district_name' => 'Mityana'],
			[ 'district_name' => 'Moroto'],
			[ 'district_name' => 'Moyo'],
			[ 'district_name' => 'Mpigi'],
			[ 'district_name' => 'Mubende'],
			[ 'district_name' => 'Mukono'],
			[ 'district_name' => 'Nabilatuk'],
			[ 'district_name' => 'Nakapiripiriti'],
			[ 'district_name' => 'Nakaseke'],
			[ 'district_name' => 'Nakasongola'],
			[ 'district_name' => 'Namayingo'],
			[ 'district_name' => 'Namisindwa'],
			[ 'district_name' => 'Namutumba'],
			[ 'district_name' => 'Napak'],
			[ 'district_name' => 'Nebbi' ],
			[ 'district_name' => 'Ngora' ],
			[ 'district_name' => 'Nsiika' ],
			[ 'district_name' => 'Ntoroko' ],
			[ 'district_name' => 'Ntungamo' ],
			[ 'district_name' => 'Nwoya' ],
			[ 'district_name' => 'Omoro' ],
			[ 'district_name' => 'Otuke' ],
			[ 'district_name' => 'Oyam' ],
			[ 'district_name' => 'Pader' ],
			[ 'district_name' => 'Pakwach' ],
			[ 'district_name' => 'Pallisa' ],
			[ 'district_name' => 'Rakai' ],
			[ 'district_name' => 'Rubanda' ],
			[ 'district_name' => 'Rubirizi' ],
			[ 'district_name' => 'Rukiga' ],
			[ 'district_name' => 'Rukungiri' ],
			[ 'district_name' => 'Serere' ],
			[ 'district_name' => 'Sheema' ],
			[ 'district_name' => 'Sironko' ],
			[ 'district_name' => 'Soroti' ],
			[ 'district_name' => 'Sembabule' ],
			[ 'district_name' => 'Tororo' ],
			[ 'district_name' => 'Wakiso' ],
			[ 'district_name' => 'Yumbe' ],
			[ 'district_name' => 'Zombo' ],
        ];

        foreach ($districts as $key => $value) {
        	District::create($value);
        }
    }
}
